FORMAT: 1A
HOST: http://example.com

# 投稿情報管理機能
ユーザーが投稿した情報を扱うAPIです。

#投稿
## 基本情報 [/api/v1/posts/{id}]
投稿情報を扱います。

### 情報取得 [GET]
投稿された情報全てを取得します。

+ Response 200 (application/json; charset=utf-8)
    + Attribute
      + id: `1` (string, required) - 投稿ID
      + title: `get_title` (string, required) - 投稿タイトル
      + text: `get_text` (string, required) - 投稿内容

+ Response 404 (application/json; charset=utf-8)
    + Attribute
      + message: `404 Not Found` (string, required) - エラーメッセージ

### 情報登録 [POST]
投稿された情報を登録します。
+ Request
    + Attribute
        + title: `post_title` (string, required) - 投稿タイトル
        + test: `post_text` (string, required) - 投稿内容

+ Response 200 (application/json; charset=utf-8)
    + Attribute

+ Response 500 (application/json; charset=utf-8)
    + Attribute
        + message: `Internal Server Error` (string, required) - エラーメッセージ

### 情報更新 [PUT]
投稿された情報を更新します。
+ Parameters
    + id: `1` (string, required) - 投稿ID
+ Request
    + Attribute
        + title: `post_title` (string, required) - 投稿タイトル
        + test: `post_text` (string, required) - 投稿内容

+ Response 200 (application/json; charset=utf-8)
    + Attribute
        + title: `post_title` (string, required) - 投稿タイトル
        + test: `post_text` (string, required) - 投稿内容

+ Response 500 (application/json; charset=utf-8)
    + Attribute
        + message: `Internal Server Error` (string, required) - エラーメッセージ

### 情報削除 [DELETE]
投稿された情報を削除します。
+ Parameters
    + id: `1` (string, required) - 投稿ID

+ Response 200 (application/json; charset=utf-8)
    + Attribute

+ Response 500 (application/json; charset=utf-8)
    + Attribute
        + message: `Internal Server Error` (string, required) - エラーメッセージ
